// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChFYx38NX8PMqwyzsCBtwlsZYTSeIv_sQ',
    appId: '1:15710401121:web:4b3cca00b828a1bd027020',
    messagingSenderId: '15710401121',
    projectId: 'tickr-30dc8',
    authDomain: 'tickr-30dc8.firebaseapp.com',
    storageBucket: 'tickr-30dc8.firebasestorage.app',
    measurementId: 'G-ZM496VCZPW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfMTdpmWe8HP4IBfj62HtKpilHNlr1iSo',
    appId: '1:15710401121:android:da94918188af0f99027020',
    messagingSenderId: '15710401121',
    projectId: 'tickr-30dc8',
    storageBucket: 'tickr-30dc8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDidsxfDNoU8Xbt-EYyHCzcfq8XFCe-eRg',
    appId: '1:15710401121:ios:00829ed80acd13b4027020',
    messagingSenderId: '15710401121',
    projectId: 'tickr-30dc8',
    storageBucket: 'tickr-30dc8.firebasestorage.app',
    iosBundleId: 'com.pvlah.tickr',
  );
}
